title: Playful Mathematician
email: me@playfulmathematician.com 
description: >- 
  Welcome to my website here, you will see many mathematical explorations!
baseurl: ""
url: "https://playfulmathematician.com"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache

include:
  - _includes/head.html

header_pages:
  - index.markdown
  - about.markdown 
  - contact.markdown
destination: out
