title: Playful Mathematician
email: My email is down
description: >- 
  Welcome to my website here you will see many mathematical explorations!
baseurl: ""
url: "https://playfulmathematician.com"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache

include:
  - _includes/head.html

header_pages:
  - index.markdown
  - about.markdown